/** Every HTML entry of the site. Used by the Vite build, the shell renderer and the tests. */
import { CITIES } from '../data/cities.ts';

/** Public address of the site (canonical links). */
export const SITE_URL = 'https://nioxxer.com';

export type PageId =
  | 'home'
  | 'search'
  | 'listing'
  | 'member'
  | 'login'
  | 'verifyEmail'
  | 'account'
  | 'publish'
  | 'boost'
  | 'admin'
  | 'help'
  | 'terms'
  | 'privacy'
  | 'legal'
  | 'rules'
  | 'notFound'
  | 'city';

export type NavTab = 'home' | 'search' | 'publish' | 'account';

export interface PageDef {
  readonly id: PageId;
  /** HTML file at the project root (Vite entry). */
  readonly file: string;
  /** Public clean URL (firebase.json `cleanUrls`). */
  readonly path: string;
  /** Bottom-bar tab highlighted on this page. */
  readonly nav: NavTab | null;
  readonly noindex: boolean;
  /** /ville/{slug} pages (generated by `npm run pages:sync`): the city shown. */
  readonly city?: { readonly slug: string; readonly name: string };
}

export const PAGES: readonly PageDef[] = [
  { id: 'home', file: 'index.html', path: '/', nav: 'home', noindex: false },
  { id: 'search', file: 'recherche.html', path: '/recherche', nav: 'search', noindex: false },
  { id: 'listing', file: 'annonce.html', path: '/annonce', nav: null, noindex: false },
  { id: 'member', file: 'membre.html', path: '/membre', nav: null, noindex: false },
  { id: 'login', file: 'connexion.html', path: '/connexion', nav: 'account', noindex: false },
  { id: 'verifyEmail', file: 'verifier-email.html', path: '/verifier-email', nav: 'account', noindex: true },
  { id: 'account', file: 'compte.html', path: '/compte', nav: 'account', noindex: true },
  { id: 'publish', file: 'publier.html', path: '/publier', nav: 'publish', noindex: true },
  { id: 'boost', file: 'booster.html', path: '/booster', nav: null, noindex: true },
  { id: 'admin', file: 'admin.html', path: '/admin', nav: null, noindex: true },
  { id: 'help', file: 'aide.html', path: '/aide', nav: null, noindex: false },
  { id: 'terms', file: 'cgu.html', path: '/cgu', nav: null, noindex: false },
  { id: 'privacy', file: 'confidentialite.html', path: '/confidentialite', nav: null, noindex: false },
  { id: 'legal', file: 'mentions-legales.html', path: '/mentions-legales', nav: null, noindex: false },
  { id: 'rules', file: 'regles.html', path: '/regles', nav: null, noindex: false },
  { id: 'notFound', file: '404.html', path: '/404', nav: null, noindex: true },
  ...CITIES.map((c): PageDef => ({
    id: 'city',
    file: `ville/${c.slug}.html`,
    path: `/ville/${c.slug}`,
    nav: 'home',
    noindex: false,
    city: { slug: c.slug, name: c.name },
  })),
];

/** Build entry name (unique, also for the 28 city pages). */
export function entryName(p: PageDef): string {
  return p.city ? `city-${p.city.slug}` : p.id;
}

export function pageByFile(file: string): PageDef | undefined {
  return PAGES.find((p) => p.file === file);
}

export function pageByPath(path: string): PageDef | undefined {
  return PAGES.find((p) => p.path === path);
}
