/**
 * Renders the block of firestore.rules that must stay identical to the TypeScript sources
 * (single source of truth, ARCHITECTURE § 5): moderation patterns, limits, cities, genres,
 * report reasons. Written into firestore.rules by scripts/sync-rules.ts; checked by
 * tests/unit/rules-sync.test.ts.
 */
import { AUDIT_TARGET_TYPES } from '../src/data/audit.ts';
import { CITIES } from '../src/data/cities.ts';
import { GENRES } from '../src/data/genres.ts';
import {
  ADULT_MIN_DAYS,
  AVATAR_URL_PATTERN,
  DATA_URL_MAX_CHARS,
  LISTING_LIFETIME_DAYS,
  PHOTOS_MAX,
  PHOTO_REF,
  PHOTOS_MIN,
  PSEUDO_PATTERN,
  RESERVED_PSEUDO_FRAGMENTS,
  STRIKES_BAN_THRESHOLD,
  TEXT_MAX,
  TEXT_MIN,
  WHATSAPP_PATTERN,
} from '../src/data/limits.ts';
import { CONTACT_PATTERN, MINOR_PATTERN, PRICE_PATTERN } from '../src/data/moderation.ts';
import { NOTIFICATION_TYPES } from '../src/data/notifications.ts';
import { REPORT_REASONS } from '../src/data/reports.ts';

export const BLOCK_START =
  '    // <shared> generated by `npm run rules:sync` from src/data — do not edit by hand';
export const BLOCK_END = '    // </shared>';

function str(value: string): string {
  if (value.includes("'") || value.includes('\\')) {
    throw new Error(`rules-shared: unsupported character in ${value}`);
  }
  return `'${value}'`;
}

/**
 * A closed list becomes ONE regex (`^(a|b|c)$`): Firestore rules stop after 1000 evaluated
 * expressions per request, and a list or map literal costs one expression per element.
 */
function oneOf(values: readonly string[]): string {
  for (const v of values) {
    if (!/^[A-Za-z0-9_-]+$/.test(v)) throw new Error(`rules-shared: unsupported value ${v}`);
  }
  return str(`^(${values.join('|')})$`);
}

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export function renderSharedBlock(): string {
  const fn = (name: string, body: string) => `    function ${name}() { return ${body}; }`;
  const lengths = Object.entries(TEXT_MIN).map(([field, min]) =>
    fn(`len${capitalize(field)}`, `[${min}, ${TEXT_MAX[field as keyof typeof TEXT_MIN]}]`),
  );
  const maxima = Object.entries(TEXT_MAX)
    .filter(([field]) => !(field in TEXT_MIN))
    .map(([field, max]) => fn(`max${capitalize(field)}`, String(max)));
  return [
    BLOCK_START,
    // Minor terms | prices | contact details, in one regex ((?s): « . » also spans new lines).
    fn('forbiddenTextPattern', str(`(?s).*(${MINOR_PATTERN}|${PRICE_PATTERN}|${CONTACT_PATTERN}).*`)),
    // The photo list joined with spaces: 1 to 5 photo references.
    fn('photoListPattern', str(`^${PHOTO_REF}( ${PHOTO_REF}){0,${PHOTOS_MAX - 1}}$`)),
    fn('pseudoPattern', str(PSEUDO_PATTERN)),
    fn('whatsappPattern', str(WHATSAPP_PATTERN)),
    fn('reservedPseudoPattern', str(`.*(${RESERVED_PSEUDO_FRAGMENTS.join('|')}).*`)),
    fn('photoUrlPattern', str(AVATAR_URL_PATTERN)),
    fn('adultMinDays', String(ADULT_MIN_DAYS)),
    fn('listingLifetimeDays', String(LISTING_LIFETIME_DAYS)),
    fn('strikesBanThreshold', String(STRIKES_BAN_THRESHOLD)),
    fn('photosMin', String(PHOTOS_MIN)),
    fn('photosMax', String(PHOTOS_MAX)),
    fn('dataUrlMaxChars', String(DATA_URL_MAX_CHARS)),
    ...lengths,
    ...maxima,
    fn('genrePattern', oneOf(GENRES)),
    fn('citySlugPattern', oneOf(CITIES.map((c) => c.slug))),
    fn('reportReasonPattern', oneOf(REPORT_REASONS)),
    fn('notificationTypePattern', oneOf(NOTIFICATION_TYPES)),
    fn('auditTargetTypePattern', oneOf(AUDIT_TARGET_TYPES)),
    BLOCK_END,
  ].join('\n');
}

/** Replaces the generated block inside the rules source. */
export function injectSharedBlock(rules: string): string {
  const start = rules.indexOf(BLOCK_START);
  const end = rules.indexOf(BLOCK_END);
  if (start < 0 || end < start) throw new Error('rules-shared: markers not found in firestore.rules');
  return rules.slice(0, start) + renderSharedBlock() + rules.slice(end + BLOCK_END.length);
}
