import type { TextProblem } from '../../src/data/moderation';

/** Legitimate texts that must be accepted (owner's examples first). */
export const ACCEPTED = [
  '25 ans',
  '1m75',
  '2 enfants',
  'né en 1995',
  'Femme de 32 ans, douce et souriante',
  'Je mesure 1m82 et je fais du sport',
  'Mère de 2 enfants, je cherche une relation sérieuse',
  'Née en 1990 à Douala',
  'En couple depuis 3 ans, nous cherchons des amis',
  'J’aime la danse, la cuisine et les voyages',
  'Homme gentil, 45 ans, divorcé',
  'Quartier Bonamoussadi, près du carrefour',
  'Disponible le week-end pour un verre',
  'Je suis franc et direct',
  'Écris-moi sur WhatsApp avec le bouton',
  'Grand frère attentionné, 28 ans',
  'J’ai 2 frères et 3 sœurs',
  'Adorable et cultivée',
  'Je cherche quelqu’un de mature',
  'Amatrice de football et de musique',
  'Lesbienne de 27 ans à Yaoundé',
  'Trans, 30 ans, fière de qui je suis',
  'Couple marié depuis 8 ans',
  'J’ai fait 5 ans d’études à Buea',
  'Je travaille dans une école comme comptable',
  'Rencontre sérieuse uniquement, pas de plan d’un soir',
  'Je fais 70 kg pour 1m70',
  'Bac+5, ingénieure',
  'Je suis née le 12 mars 1988',
  'Cherche homme de 35 à 50 ans',
  'Sortie au restaurant ou au cinéma',
  'Teint clair, yeux marron, 1m65',
  '27 F cherche homme',
  'H 40 ans, 1m80, 85 kg',
  'Je fais 70 k de développé couché',
];

/** Texts that must be refused, with the expected reason. */
export const REFUSED: readonly [string, TextProblem][] = [
  ['Je suis mineure mais mature', 'minor'],
  ['Jeune fille de 16 ans', 'minor'],
  ['J’ai 17 ans', 'minor'],
  ['17ans et motivée', 'minor'],
  ['Ado cherche ami', 'minor'],
  ['Adolescente sérieuse', 'minor'],
  ['Lycéenne disponible', 'minor'],
  ['lyceenne disponible', 'minor'],
  ['Collégienne', 'minor'],
  ['écolière', 'minor'],
  ['ECOLIERE', 'minor'],
  ['schoolgirl', 'minor'],
  ['teen sexy', 'minor'],
  ['Petite fille sage', 'minor'],
  ['Gamine de 15', 'minor'],
  ['I am 16 years old', 'minor'],
  ['Prix : 10 000 f', 'price'],
  ['10000 FCFA la nuit', 'price'],
  ['5k la passe', 'price'],
  ['2000frs seulement', 'price'],
  ['15 000 francs', 'price'],
  ['Mes tarifs sont raisonnables', 'price'],
  ['Massage payant', 'price'],
  ['Short time ou long time', 'price'],
  ['30 mille par nuit', 'price'],
  ['Envoie money d’abord', 'price'],
  ['Escort girl à Akwa', 'price'],
  ['Rémunération à discuter', 'price'],
  ['Appelle-moi au 6 78 80 24 47', 'contact'],
  ['Mon numéro : 678802447', 'contact'],
  ['+237 678 802 447', 'contact'],
  ['wa.me/237678802447', 'contact'],
  ['Écris à moi@exemple.com', 'contact'],
  ['Voir www.monsite.cm', 'contact'],
  ['Ligne 1\nJ’ai 16 ans', 'minor'],
  ['J’ai seize ans', 'minor'],
  ['dix-sept ans et sage', 'minor'],
  ['17 yo', 'minor'],
  ['25k seulement', 'price'],
  ['500f', 'price'],
  ['6 - 78 - 80 - 24 - 47', 'contact'],
];
